### ISSUE TITLE
Inquire image size

### ISSUE THREAD

**Issue by kt9292** [Huang-ShiRui/Semi-UIR#1]
Thanks to your source code.
your code operate very well.
but it leak memory or shortage of memory when i process images which is 1280 x 720 size.
Did you try processing over than 640 x 480?

or could you advice how to process 1280 x 720 size?
My GPU is GeForce RTX 2080 SUPER Mobile / Max-Q

**Comment by Huang-ShiRui** [comment]
Thanks for your question! Our test code can handle images with solution 1280×720 on two NVIDIA 3090 GPUs. If you don't have such equipment, you can try to crop the original large-scale picture into several parts and process them parallelly. Looking forward to your new results.

**Comment by kt9292** [comment]
Thank you for your answer.
Unfortunately, I don't have enough gpu power.
So, I am finding method to convert your code(based mmcv) to tensorrt(or onnx)
but, i can not find how to convert... (i try to [mmcv to onnx](https://mmcv.readthedocs.io/en/latest/deployment/onnxruntime_op.html) but this is not operated well)
Could you advice converting your code?

really thanks
