### ISSUE TITLE
Running with your pretrained model to get the reported PSNR

### ISSUE THREAD

**Issue by weilegexiang** [Huang-ShiRui/Semi-UIR#13]
Hi, 
    I greatly admire your work~  I attempted to reproduce the PSNR results reported in your Tab. 1 of the paper, but I only get 22.9 on testR (the reported one is 24.6), and 22.3 on testS (23.4), the SSIM is identical to your paper. Is there something wrong with the provided pretrained model? or if you can share me with the test code for reproducing the PSNR. 

   Thank you !

**Comment by weilegexiang** [comment]
No question~  Thank you ~

**Comment by zxiol** [comment]
Hello, may I ask which specific images you used to test the model? It seems that the author did not provide a specific partition of the dataset he used. 
Thank you!

**Comment by weilegexiang** [comment]
> Hello, may I ask which specific images you used to test the model? It seems that the author did not provide a specific partition of the dataset he used. Thank you!

Hi, they may reported the PSNR-y other than the PSNR.

**Comment by zxiol** [comment]
Thank you very much. The author mentioned in the paper that 800 pairs of images were used from a synthetic dataset, but I am not sure how 800 pairs of images were selected from ten types of water quality. Do you know?

**Comment by weilegexiang** [comment]
> Thank you very much. The author mentioned in the paper that 800 pairs of images were used from a synthetic dataset, but I am not sure how 800 pairs of images were selected from ten types of water quality. Do you know?

I have no their data for training and testing, but as I known, they ever released their whole datasets, but now, it's gone.

**Comment by zxiol** [comment]
So it seems difficult to reproduce the results of the paper. Is the pre trained model provided by the author the final model of the paper?https://github.com/Huang-ShiRui/Semi-UIR/tree/14eb75d78a405cdc1f259a5ccc84dc90a63e8c13/pretrained

**Comment by weilegexiang** [comment]
> So it seems difficult to reproduce the results of the paper. Is the pre trained model provided by the author the final model of the paper?https://github.com/Huang-ShiRui/Semi-UIR/tree/14eb75d78a405cdc1f259a5ccc84dc90a63e8c13/pretrained

I think the provided model can get the results reported in the paper, I tested several real images, and it seems the model works.

**Comment by zxiol** [comment]
Thank you for your answer. Good luck
