### ISSUE TITLE
On the partition problem of training sets

### ISSUE THREAD

**Issue by zxiol** [Huang-ShiRui/Semi-UIR#17]
Hello, your training set uses 800 pairs of synthetic datasets, among which there are ten types of water quality in the synthetic dataset. Can you tell me that 800 pairs of datasets extract 80 images from each water quality type? And can the image content extracted from each water quality type overlap or not? (For example, in type I water, if the 18th image is extracted, can the 18th image still be extracted in other types of water?)
Thank you and good luck！

**Comment by zxiol** [comment]
Reproduced the author's paper results, very good work

**Comment by t22786959** [comment]
sorry, may i ask you how to reproduce the paper results score, it seems like the author didn't release the training testing validating datasets ~ thanks

**Comment by zxiol** [comment]
> sorry, may i ask you how to reproduce the paper results score, it seems like the author didn't release the training testing validating datasets ~ thanks

Sorry, I just saw the message. I randomly divided the dataset, trained and tested it using the randomly divided dataset.
