### ISSUE TITLE
Datasets download link not working

### ISSUE THREAD

**Issue by pksvision** [Huang-ShiRui/Semi-UIR#2]
Congratulations, great work.

The link to download dataset in readme isn't working. Could you check once and correct it?

**Comment by pksvision** [comment]
Thank you so much for the quick response. 

BTW, val.zip consists of ~205 images, whereas in paper you've mentioned 200 images for testing (testS + testR). 

Could you also please correct me on this?

**Comment by Huang-ShiRui** [comment]
Sure, val.zip contains our validation set, our Testset which contains several benchmarks will be released later on.

**Comment by pksvision** [comment]
Waiting for it, thank you for the response!
