### ISSUE TITLE
Question about the LA data

### ISSUE THREAD

**Issue by zhangxun97** [Huang-ShiRui/Semi-UIR#3]
The inputs of your network are raw image and LA image. So, I want know what is the LA?  How can I get the LA for my own test data?
Looking forward to your reply! Thanks!

**Comment by Huang-ShiRui** [comment]
LA indicates illumination map, you can run the 'estimate_illumination.py' to get illumination map of your test data.

**Comment by zhangxun97** [comment]
Thanks a lot!
