### ISSUE TITLE
└── unlabeled└── candidate

### ISSUE THREAD

**Issue by zhuyr97** [Huang-ShiRui/Semi-UIR#4]
What does the candidate directory contain?

**Comment by Huang-ShiRui** [comment]
It contains the reliable pseudo labels from the reliable bank, you can run 'create_candidate.py' to initialize the reliable bank.

**Comment by kkllww** [comment]
你好，我想问一下你是否运行这个程序了，运行出来的图片是全黑吗，如果不是应该是什么样子的。
