### ISSUE TITLE
Evaluation Code

### ISSUE THREAD

**Issue by zinuoli** [Huang-ShiRui/Semi-UIR#5]
Hi, could you please upload your evaluation code since there is a bit difference between distinct repo of UIQM, UCIQE and MUSIQ?

**Comment by Huang-ShiRui** [comment]
Thanks for your question. We used implementation of MUSIQ meatric as follows: 
MUSIQ: https://github.com/chaofengc/IQA-PyTorch
The other two indicators will be confirmed after I go back to school.

**Comment by ZinuoLi** [comment]
Thanks for replying. I will be looking forward to your codes of other two metrics.

**Comment by Huang-ShiRui** [comment]
UCIQE：https://github.com/JOU-UIP/UCIQE
The MATLAB implementation of UIQM has been uploaded.
