### ISSUE TITLE
model.pyFF模块里面x,和residual形状不一致的问题

### ISSUE THREAD

**Issue by hushuaiouc** [Huang-ShiRui/Semi-UIR#6]
model.py代码有问题，为什么会出现AFF模块里面x,和residual形状不一致的问题呢
![image](https://user-images.githubusercontent.com/58196478/232263293-a3f0871f-fc21-466b-8146-17a7c147ef23.png)

**Comment by Huang-ShiRui** [comment]
网络里面有上下采样，输入图像的宽高需要是8的倍数
