### ISSUE TITLE
About candidate

### ISSUE THREAD

**Issue by kkllww** [Huang-ShiRui/Semi-UIR#8]
When I run create_ After the candidate. py, it was found that the images in the candidate are all black. May I ask why this is

**Comment by Huang-ShiRui** [comment]
We constructed all black tensors just for the initialization of the reliable bank.

**Comment by kkllww** [comment]
thanks，i think that i have understanded.



---Original---
From: ***@***.***&gt;
Date: Fri, Apr 28, 2023 16:14 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Huang-ShiRui/Semi-UIR] About candidate (Issue #8)




 
We constructed all black tensors just for the initialization of the reliable bank.
